In [1]:
#append - retorna uma copia do array com os valores indexados

import numpy as np

In [2]:
a = np.array([1,2,3])

In [4]:
np.append(a, [4,5,6])

array([1, 2, 3, 4, 5, 6])

In [5]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [25]:
np.append(a, [[5,6]])

array([1, 2, 3, 5, 6])

In [50]:
np.append(a, [[5,6]], axis=0)

ValueError: all the input arrays must have same number of dimensions

In [59]:
np.append(a, [[5,6,7]], axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [60]:
a.ndim

1

In [36]:
a2 = np.array([1,2,3])
a2.ndim

1