In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])

In [3]:
np.insert(arr, 2, 15) # inserir elemento 15 na posicao 2

array([ 1,  2, 15,  3])

In [5]:
a = np.array([[1,2],[3,4]])
print(a)
print(a.ndim) # numero dimensoes

[[1 2]
 [3 4]]
2


In [7]:
print(a.sum(axis=0)) # soma first eixo - vertical
print(a.sum(axis=1)) # soma first eixo - horizontal

[4 6]
[3 7]


In [7]:
print(a.sum(axis=1)) # soma segundo eixo - horizontal

[3 7]


In [8]:
np.insert(a, 1, 5, axis=1)

array([[1, 5, 2],
       [3, 5, 4]])

In [9]:
np.insert(a, 0, 5, axis=0)

array([[5, 5],
       [1, 2],
       [3, 4]])