In [2]:
import numpy as np

In [11]:
gil_pts = [20, 30, 40, 15]
pedro_pts = [100, 24, 48, 23]
maria_pts = [92, 22, 34, 12]
gued_pts = [12, 34, 12, 43]

pontos = np.array([gil_pts, pedro_pts, maria_pts, gued_pts])

In [6]:
pontos

array([[ 20,  30,  40,  15],
       [100,  24,  48,  23],
       [ 92,  22,  34,  12],
       [ 12,  34,  12,  43]])

In [8]:
pontos[0]

array([20, 30, 40, 15])

In [10]:
pontos[1][0]

100

In [3]:
my_data = np.arange(0,20) # criando array de 0 até 19
print(my_data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [5]:
matriz_transformada = np.reshape(my_data, (5,4)) # transformando array em matriz 5x4
print(matriz_transformada)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [8]:
matriz_transformada[2,2] # consulta elemento na linha 2, coluna 2

10

In [22]:
pontos.item(10) # consulta de elemento por posição

34

In [19]:
m1 = ['python', 'eh', 'legal']
m2 = ['gued', 'eh', 'gostoso']
m3 = [10, 20, 30]

[m1, m2, m3]

[['python', 'eh', 'legal'], ['gued', 'eh', 'gostoso'], [10, 20, 30]]

In [20]:
np.array([m1, m2, m3])

array([['python', 'eh', 'legal'],
       ['gued', 'eh', 'gostoso'],
       ['10', '20', '30']], dtype='<U7')

In [24]:
notas = np.array([7, 6.5, 8.7, 9, 10])

for i in notas:
    if i <= 8:
        print(i)

7.0
6.5


In [25]:
print(notas.item(3))

9.0


4