In [2]:
import numpy

In [4]:
a = numpy.array([10, 20, 30, 40])
a

array([10, 20, 30, 40])

In [6]:
type(a)

numpy.ndarray

In [10]:
mat = numpy.array([[1,2], [3,4]])
mat

array([[1, 2],
       [3, 4]])

In [13]:
print(mat[1,1]) 
print(mat[-1,-1])

4
4


In [15]:
mat[1,:] # exibindo elementos de todas as colunas na segunda linha

array([3, 4])

In [17]:
mat[:, 0] # exibindo elementos de todas as linhas na primeira coluna

array([1, 3])

In [20]:
mat.transpose() # matriz transposta

array([[1, 3],
       [2, 4]])

In [22]:
m1 = numpy.array([[1, 2], [3, 4]])
m2 = numpy.array([[5, 6], [7, 8]])
m1 + m2

# operações tudo continua normal

array([[ 6,  8],
       [10, 12]])

In [25]:
m3 = numpy.array([1,2,3,4])
m3.sum()

10

In [27]:
m3.argmax() # indice do maior elemento do array

3

In [ ]:
m3.argmin(WW)