In [6]:
l = [20, 30, 10, 40]
print(l[1:3])
print(l[::2])

[10, 30, 50]
[50]


In [9]:
import numpy as np
a = np.array([10, 30, 50, 70])
a

array([10, 30, 50, 70])

In [10]:
print(a[1:3])
print(a[::2])

[30 10]
[20 10]


In [14]:
l

[20, 30, 10, 40]

In [13]:
l2 = l[:]
l2

[20, 30, 10, 40]

In [16]:
l2[0] = 1000
print(l)
print(l2)

[20, 30, 10, 40]
[1000, 30, 10, 40]


In [18]:
b = a[:]
b

array([20, 30, 10, 40])

In [20]:
b[0] = 1000
print(a)
print(b)

[1000   30   10   40]
[1000   30   10   40]


In [22]:
b[:] = 42
a

array([42, 42, 42, 42])

In [11]:
g = a.copy()
g

array([10, 30, 50, 70])

In [19]:
g[0] = 902
print(g)
print(a)

[902  30  50  70]
[10 30 50 70]
